apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          # http:
          #   endpoint: 0.0.0.0:4318

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "otel-collector.default.svc.cluster.local:4317"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
  annotations:
    sidecar.opentelemetry.io/inject: "true" # WRONG
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
      annotations:
        sidecar.opentelemetry.io/inject: "true" # CORRECT
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: flaskapp
          image: thongle0610/flask-app:v0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"  # Collector's OTLP endpoint
